[package]
name = "year2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc", version = "0.1.0" }
regex = "1.11.1"
itertools = "0.13.0"
combinatorial = "0.2.0"
